name: Docker Build Push
on: [push]
jobs:
  vm-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.repository }} @ ${{ github.ref }}"
        name: hi
      - run: docker version
        name: docker version
      - run: ls -la
      - uses: actions/checkout@v2
        name: checkout code
        with:
          fetch-depth: 0
          submodules: recursive
      - run: ls -la
      - run: docker build -t nftmart/web-app:${{ github.sha }} .
        name: docker build
      - run: docker images
        name: docker images
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: docker push nftmart/web-app:${{ github.sha }}
        name: docker push

      - run: |
          docker tag nftmart/web-app:${{ github.sha }} nftmart/web-app
          docker push nftmart/web-app
        name: docker push latest

      - name: docker push main
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag nftmart/web-app:${{ github.sha }} nftmart/web-app:main
          docker push nftmart/web-app:main

      - name: docker push test
        if: github.ref == 'refs/heads/test'
        run: |
          docker tag nftmart/web-app:${{ github.sha }} nftmart/subql:test
          docker push nftmart/web-app:test
